{{- if .Values.cleanup.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: cleanup-role
  namespace: {{ include "dbt.namespace" . }}
  labels:
    {{- include "dbt.labels" . | nindent 4 }}
    app.kubernetes.io/component: pod-cleanup
rules:
  - apiGroups: [""]
    resources:
      - pods
    verbs:
      - get
      - list
      - delete
{{- end }}