apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: master
  namespace: argocd
spec:
  project: default
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  source:
    repoURL: git@url
    targetRevision: master
    path: .
    helm:
      valueFiles:
        - values.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      enabled: true
