apiVersion: v2
appVersion: 3.3.0
description: 'custom apicurio registry chart'
keywords:
- apicurio
- schema-registry
maintainers:
  - name: Truong Thanh Binh
    email: dev.binhtt@gmail.com
    url: https://github.com/BevisDev
name: schema-registry
version: 0.1.0
