apiVersion: v2
name: kafka-topics
description: Kafka Topic Definitions
type: application
version: 0.1.0
appVersion: "4.2.0"
keywords:
  - kafka
  - cdc
  - strimzi
maintainers:
  - name: Truong Thanh Binh
    email: dev.binhtt@gmail.com
    url: https://github.com/BevisDev
